import { Helmet } from "react-helmet-async";

export default function CookieSheetPrivacy() {
  return (
    <>
      <Helmet>
        <title>Cookie Sheet — Privacy Policy | Opn.li</title>
        <meta name="description" content="Privacy policy for Cookie Sheet, a free browser extension by Opn.li that shows you what cookies websites store in your browser." />
      </Helmet>
      <div className="min-h-screen bg-white">
        <header className="border-b border-gray-100">
          <div className="mx-auto max-w-[720px] px-6 py-6">
            <a href="https://opn.li" className="text-lg font-semibold tracking-tight text-gray-900">Opn.li</a>
          </div>
        </header>

        <main className="mx-auto max-w-[720px] px-6 py-12">
          <article className="prose prose-gray max-w-none prose-headings:text-gray-900 prose-p:text-gray-700 prose-p:leading-relaxed prose-li:text-gray-700 prose-strong:text-gray-900 prose-a:text-blue-600 hover:prose-a:text-blue-800">
            <h1>Cookie Sheet — Privacy Policy</h1>

            <p><strong>Last updated: April 9, 2026</strong></p>

            <p>Cookie Sheet is a free browser extension developed by Opn.li ("we," "us," or "our"). This privacy policy explains what data Cookie Sheet accesses, how it is used, and how it is protected.</p>

            <h2>What Cookie Sheet Does</h2>
            <p>Cookie Sheet reads the cookies stored in your browser for the websites you visit. It classifies these cookies into human-readable categories (such as advertising, analytics, social, functional, essential, or unknown) and displays them to you in a popup when you click the Cookie Sheet icon in your browser toolbar.</p>
            <p>Cookie Sheet is a transparency tool. It shows you what cookies exist in your browser — it does not block, modify, or delete cookies in this version.</p>

            <h2>What Data Cookie Sheet Accesses</h2>
            <p>Cookie Sheet accesses the following data:</p>
            <ul>
              <li><strong>Browser cookies</strong> for the websites you visit, using the browser's standard cookies API. This includes: cookie name, domain, expiration date, and cookie attributes (secure, httpOnly, sameSite).</li>
              <li><strong>Page metadata</strong> for the current website, including: page title, favicon URL, and privacy policy link (if present on the page). This is used to provide context about the website in the Cookie Sheet popup.</li>
            </ul>

            <h2>What Cookie Sheet Does NOT Do</h2>
            <ul>
              <li><strong>Cookie Sheet does not collect, transmit, or store any of your data on any server.</strong> All data processing happens locally in your browser.</li>
              <li>Cookie Sheet does not send any information to Opn.li, to any third party, or to any remote server.</li>
              <li>Cookie Sheet does not track your browsing history.</li>
              <li>Cookie Sheet does not modify, block, or delete any cookies.</li>
              <li>Cookie Sheet does not inject any content into web pages.</li>
              <li>Cookie Sheet does not use any analytics, telemetry, or crash reporting.</li>
              <li>Cookie Sheet does not require an account to use.</li>
              <li>Cookie Sheet does not display advertisements.</li>
            </ul>

            <h2>Data Storage</h2>
            <p>All data generated by Cookie Sheet (cookie classifications, visitorCARD data) is stored locally in your browser using the browser's built-in storage APIs (chrome.storage.session). This data is temporary and is cleared when you close your browser. No data is stored persistently on your device or transmitted externally.</p>

            <h2>Permissions Explained</h2>
            <p>Cookie Sheet requests the following browser permissions:</p>
            <ul>
              <li><strong>cookies</strong>: Required to read the cookies stored in your browser for the current website. This is the core functionality of the extension.</li>
              <li><strong>activeTab</strong>: Required to identify the current website you are viewing, so Cookie Sheet can display cookies relevant to that site.</li>
              <li><strong>storage</strong>: Required to temporarily store cookie classification results so the popup can display them when you click the icon.</li>
              <li><strong>host_permissions (&lt;all_urls&gt;)</strong>: Required because Cookie Sheet needs to read cookies for any website you visit, not just specific pre-defined websites. Without this permission, Cookie Sheet could not show you cookies on the sites you actually use.</li>
            </ul>

            <h2>Third-Party Services</h2>
            <p>Cookie Sheet does not use any third-party services, APIs, SDKs, analytics tools, or advertising networks. There are no third-party dependencies that access your data.</p>

            <h2>Children's Privacy</h2>
            <p>Cookie Sheet does not knowingly collect any personal information from children under the age of 13.</p>

            <h2>Future Account Features</h2>
            <p>In a future version, Cookie Sheet may offer an optional account feature through opn.li that allows you to sync your cookie preferences across devices. If and when this feature is introduced, it will be entirely optional, clearly disclosed, and will require your explicit consent before any data is transmitted. This privacy policy will be updated before any such feature is released.</p>

            <h2>Chrome Web Store User Data Policy Compliance</h2>
            <p>Cookie Sheet complies with the Chrome Web Store User Data Policy, including the Limited Use requirements. Specifically:</p>
            <ul>
              <li>Cookie Sheet uses the data it accesses (browser cookies and page metadata) solely to provide its core user-facing feature: displaying human-readable cookie information to you.</li>
              <li>Cookie Sheet does not transfer user data to any third party.</li>
              <li>Cookie Sheet does not use user data for advertising, analytics, or any purpose unrelated to the extension's stated functionality.</li>
              <li>Cookie Sheet does not sell user data.</li>
            </ul>

            <h2>Changes to This Privacy Policy</h2>
            <p>If we make changes to this privacy policy, we will update the "Last updated" date at the top of this page. We encourage you to review this page periodically.</p>

            <h2>Open Source</h2>
            <p>Cookie Sheet is open source. You can review the complete source code to verify these privacy claims at: <a href="https://github.com/mikeoz/cookie-sheet" target="_blank" rel="noopener noreferrer">https://github.com/mikeoz/cookie-sheet</a></p>

            <h2>Contact</h2>
            <p>If you have questions about this privacy policy or Cookie Sheet, you can reach us at:</p>
            <ul>
              <li>Email: <a href="mailto:privacy@opn.li">privacy@opn.li</a></li>
              <li>Website: <a href="https://opn.li" target="_blank" rel="noopener noreferrer">https://opn.li</a></li>
            </ul>

            <hr />

            <p className="text-center"><strong>Opn.li — Trust infrastructure for the agentic web</strong></p>
            <p className="text-center italic">My data + Your AI + My control = Living Intelligence</p>
          </article>
        </main>

        <footer className="border-t border-gray-100">
          <div className="mx-auto max-w-[720px] px-6 py-6 text-center text-sm text-gray-400">
            © {new Date().getFullYear()} Opn.li. All rights reserved.
          </div>
        </footer>
      </div>
    </>
  );
}
